name: Lint

on: [push]

jobs:
  lint:
    name: Check coding style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Lint the project
        run: uv run ruff check && uv run ruff format --check
